### ISSUE TITLE
1.18.1 | Tag not working. Unsure if [AFK] is overlapping. (Don't have any AFK plugin...)

### ISSUE THREAD

**Issue by THE-muth** [re-ovo/VirtualTag#2]
I've been tinkering with a bunch of different ways. I don't have any AFK Plugin installed that I know of either.
![image](https://user-images.githubusercontent.com/96262223/146437580-87f8c97e-6cbe-49fa-8d44-4615d247952e.png)
Edit: 
![image](https://user-images.githubusercontent.com/96262223/146438633-65eb57e4-4d92-4a61-b1a8-bfca04194ad7.png)

**Comment by re-ovo** [comment]
what's your server version, did u installed ProtocolLib?

**Comment by THE-muth** [comment]
> what's your server version, did u installed ProtocolLib?

I have installed ProtocolLib, 1.18.1

**Comment by re-ovo** [comment]
we better discuss at discord server

**Comment by THE-muth** [comment]
Surely, hmu with the server link (I don't know where I could find it) Would really appreciate it.

**Comment by re-ovo** [comment]
discord.gg/6esJfwP5fF
